/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/neutral/neutralTheme.ts
 * Command: astryx theme build src/themes/neutral/neutralTheme.ts --out src/themes/neutral/theme.css
 * Generated: 2026-07-10T17:32:43.791Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
